name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        name: Check
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - name: cargo check
              run: cargo check
    test:
        runs-on: ubuntu-latest
        name: Test
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - name: cargo test
              run: cargo test
    # uncomment to enable clippy lints
    clippy:
        runs-on: ubuntu-latest
        name: Lint (clippy)
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  components: clippy
                  override: true
            - name: cargo clippy
              run: cargo clippy -- -D warnings
